server:
  port: 8080

spring:
  application:
    name: dotachess-core

  datasource:
    url: jdbc:postgresql://192.168.0.131:5432/dotachess
    username: postgres
    password: intmain321890
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: "lol xddd"

management:
  endpoints:
    web:
      exposure:
        include: beans